name = "talktech-next-on-pages"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# ===============================
# PRODUCTION
# ===============================
[env.production.vars]
# --- App & routing ---
SITE_ORIGIN = "https://talktech.io"
ENVIRONMENT = "production"

# --- API route -> Worker integration (PLAIN TEXT) ---
# URL of your contact Worker (route or workers.dev)
CONTACT_WORKER_URL = "https://contactworker.sdspirek.workers.dev"

# --- Turnstile (site key is public / plain text) ---
TURNSTILE_SITE_KEY = "0x4AAAAAABunO9-oW-iHJneR"

# --- Optional rate limits (plain text knobs) ---
RATE_LIMIT_WINDOW_SECS = "60"
RATE_LIMIT_MAX = "5"
NOTIFICATION_EMAIL = "contact@talktech.io"

# D1 binding for local/dev parity 
[[env.production.d1_databases]]
binding = "TALKTECH_DB"
database_name = "talktech-db"          
database_id = "605da4e8-9f81-4560-b9dd-e47d590ba221"  

"d1_databases": [{
    "binding": "DB",
    "database_name": "talktech-db",
    "database_id": "605da4e8-9f81-4560-b9dd-e47d590ba221"
 }]

# KV binding for optional rate limiting 
[[env.production.kv_namespaces]]
binding = "TALKTECH_KV"
id = "b023ff2f14ae401aa81d1bb963f96a58"

# ===============================
# PREVIEW / STAGING
# ===============================
[env.preview.vars]
SITE_ORIGIN = "https://talktech.pages.dev"
ENVIRONMENT = "preview"

# Can point to the same Worker or a staging Worker route
CONTACT_WORKER_URL = "https://contactworker.sdspirek.workers.dev"
NOTIFICATION_EMAIL = "contact@talktech.io"

TURNSTILE_SITE_KEY = "0x4AAAAAABunO9-oW-iHJneR"

# Looser limits for testing
RATE_LIMIT_WINDOW_SECS = "60"
RATE_LIMIT_MAX = "10"

# (Optional) KV in preview too
[[env.preview.kv_namespaces]]
binding = "TALKTECH_KV"
id = "b023ff2f14ae401aa81d1bb963f96a58"
