name = "talktech-next-on-pages"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Production environment
[env.production.vars]
SITE_ORIGIN = "https://talktech.io"
RATE_LIMIT_WINDOW_SECS = "60"
RATE_LIMIT_MAX = "5"
TURNSTILE_SITE_KEY = "0x4AAAAAABunO9-oW-iHJneR"

# Database binding (update database_id after creating)
[[env.production.d1_databases]]
binding = "TALKTECH_DB"
database_name = "talktech-db"
database_id = "26a7a5e6-1e5e-4c00-a3d3-7901b718a31f"  # Fill this after: wrangler d1 create talktech-db

# KV binding (optional - update id after creating)
[[env.production.kv_namespaces]]
binding = "TALKTECH_KV"
id = "b023ff2f14ae401aa81d1bb963f96a58"  # Fill this after: wrangler kv:namespace create "TALKTECH_KV"

# Preview environment (for staging/pull requests)
[env.preview.vars]
SITE_ORIGIN = "https://talktech.pages.dev"
RATE_LIMIT_WINDOW_SECS = "60"  
RATE_LIMIT_MAX = "10"  # More lenient for testing
TURNSTILE_SITE_KEY = "0x4AAAAAABunO9-oW-iHJneR"

# Preview can use same database for testing
[[env.preview.d1_databases]]
binding = "TALKTECH_DB"
database_name = "talktech-db"
database_id = "26a7a5e6-1e5e-4c00-a3d3-7901b718a31f"  # Same as production or separate test DB

# 🔐 SECRETS - Set these via CLI (never in this file):
# wrangler secret put TURNSTILE_SECRET_KEY --env production
# wrangler secret put CF_CONTACT_WEBHOOK --env production
